#include "ninja.h"

#include <unistd.h>
#include <fcntl.h>

Ninja::Ninja(const char* file) : fs(file){
	this->fs
	<< "#\n"
	<< "# Generated by meson-lua\n"
	<< "# DO NOT EDIT MANUALLY\n"
	<< "#\n";
}
